FROM python:3.11-slim

ARG GIT_SHA=""
ARG BUILD_VERSION=""
ARG DOCKER_TAG=""

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    GIT_SHA=${GIT_SHA} \
    BUILD_VERSION=${BUILD_VERSION} \
    DOCKER_TAG=${DOCKER_TAG}

WORKDIR /app

COPY pyproject.toml README.md LICENSE ./
COPY src ./src

RUN pip install --no-cache-dir .

ENV MCP_TRANSPORT=http \
    MCP_HOST=0.0.0.0 \
    MCP_PORT=7860 \
    MCP_PATH=/mcp \
    MCP_STATELESS_HTTP=true

EXPOSE 7860

CMD ["grok-search"]
